In [1]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\dell\anaconda3\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (3.11.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py>=3.11.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\dell\anaconda3\lib\site-packages (from tensorflow) (0.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dell\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in c:\users\dell\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.8)
Requirement already satisfied: pillow in c:\users\dell\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.1.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\dell\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\dell\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\dell\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\dell\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in c:\users\dell\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\dell\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\dell\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\dell\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dell\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\dell\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.0)

In [2]:
import tensorflow as tf
print(tf.__version__)

2.20.0

In [3]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [4]:
df = pd.DataFrame({
    "soil_moisture": [12.3, 8.7, 18.2, 10.5, 20.1, 14.9, 7.8, 9.2, 16.4, 11.8,
                      19.5, 6.9, 13.7, 15.6, 8.3, 10.1, 18.8, 9.7, 12.9, 7.2],
    "temperature_c": [25.1, 30.4, 22.3, 28.7, 19.6, 24.5, 31.2, 29.5, 23.0, 27.6,
                      21.1, 32.0, 26.2, 24.0, 30.9, 28.3, 20.5, 29.1, 25.3, 31.7],
    "sunlightz_hours": [6.5, 8.2, 4.1, 7.8, 3.2, 5.0, 9.1, 8.4, 4.9, 6.8,
                        3.9, 9.3, 5.7, 4.8, 8.7, 7.1, 3.6, 7.9, 5.4, 8.9],
    "needsz_water": [1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
                     0, 1, 0, 0, 1, 1, 0, 1, 0, 1]
})

In [5]:
df

    soil_moisture  temperature_c  sunlightz_hours  needsz_water
0            12.3           25.1              6.5             1
1             8.7           30.4              8.2             1
2            18.2           22.3              4.1             0
3            10.5           28.7              7.8             1
4            20.1           19.6              3.2             0
5            14.9           24.5              5.0             0
6             7.8           31.2              9.1             1
7             9.2           29.5              8.4             1
8            16.4           23.0              4.9             0
9            11.8           27.6              6.8             1
10           19.5           21.1              3.9             0
11            6.9           32.0              9.3             1
12           13.7           26.2              5.7             0
13           15.6           24.0              4.8             0
14            8.3           30.9              8.7             1
15           10.1           28.3              7.1             1
16           18.8           20.5              3.6             0
17            9.7           29.1              7.9             1
18           12.9           25.3              5.4             0
19            7.2           31.7              8.9             1

In [6]:
X=df.drop('needsz_water',axis=1)
y=df['needsz_water']

In [7]:
X_min=X.min()
X_max=X.max()
X_scaled=(X-X_min)/(X_max-X_min+1e-8)

In [8]:
X_scaled

    soil_moisture  temperature_c  sunlightz_hours
0        0.409091       0.443548         0.540984
1        0.136364       0.870968         0.819672
2        0.856061       0.217742         0.147541
3        0.272727       0.733871         0.754098
4        1.000000       0.000000         0.000000
5        0.606061       0.395161         0.295082
6        0.068182       0.935484         0.967213
7        0.174242       0.798387         0.852459
8        0.719697       0.274194         0.278689
9        0.371212       0.645161         0.590164
10       0.954545       0.120968         0.114754
11       0.000000       1.000000         1.000000
12       0.515152       0.532258         0.409836
13       0.659091       0.354839         0.262295
14       0.106061       0.911290         0.901639
15       0.242424       0.701613         0.639344
16       0.901515       0.072581         0.065574
17       0.212121       0.766129         0.770492
18       0.454545       0.459677         0.360656
19       0.022727       0.975806         0.934426

In [9]:
X_train, X_test, y_train, y_test = train_test_split( X_scaled, y, test_size=0.25, random_state=42)

In [10]:
model=keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid'),
])

In [11]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [13]:
history=model.fit(
    X_train.values,y_train.values,
    validation_data=( X_train.values,y_train.values),
    epochs=100,batch_size=5, verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 1.0000 - loss: 0.4151 - val_accuracy: 1.0000 - val_loss: 0.4137
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 105ms/step - accuracy: 1.0000 - loss: 0.4131 - val_accuracy: 1.0000 - val_loss: 0.4118
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.4121 - val_accuracy: 1.0000 - val_loss: 0.4098
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 1.0000 - loss: 0.4094 - val_accuracy: 1.0000 - val_loss: 0.4079
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.4079 - val_accuracy: 1.0000 - val_loss: 0.4059
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.4054 - val_accuracy: 1.0000 - val_loss: 0.4040
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4034 - val_accuracy: 1.0000 - val_loss: 0.4021
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.4015 - val_accuracy: 1.0000 - val_loss: 0.4002
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.3998 - val_accuracy: 1.0000 - val_loss: 0.3983
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3979 - val_accuracy: 1.0000 - val_loss: 0.3964
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 1.0000 - loss: 0.3961 - val_accuracy: 1.0000 - val_loss: 0.3945
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 105ms/step - accuracy: 1.0000 - loss: 0.3946 - val_accuracy: 1.0000 - val_loss: 0.3926
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.3926 - val_accuracy: 1.0000 - val_loss: 0.3908
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.3903 - val_accuracy: 1.0000 - val_loss: 0.3890
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.3889 - val_accuracy: 1.0000 - val_loss: 0.3872
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 1.0000 - loss: 0.3866 - val_accuracy: 1.0000 - val_loss: 0.3854
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.3853 - val_accuracy: 1.0000 - val_loss: 0.3836
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.3830 - val_accuracy: 1.0000 - val_loss: 0.3818
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.3812 - val_accuracy: 1.0000 - val_loss: 0.3800
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.3796 - val_accuracy: 1.0000 - val_loss: 0.3782
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 1.0000 - loss: 0.3783 - val_accuracy: 1.0000 - val_loss: 0.3765
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.3765 - val_accuracy: 1.0000 - val_loss: 0.3747
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.3745 - val_accuracy: 1.0000 - val_loss: 0.3730
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.3730 - val_accuracy: 1.0000 - val_loss: 0.3712
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3710 - val_accuracy: 1.0000 - val_loss: 0.3695
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.3692 - val_accuracy: 1.0000 - val_loss: 0.3678
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 1.0000 - loss: 0.3678 - val_accuracy: 1.0000 - val_loss: 0.3661
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.3655 - val_accuracy: 1.0000 - val_loss: 0.3644
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.3639 - val_accuracy: 1.0000 - val_loss: 0.3627
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.3622 - val_accuracy: 1.0000 - val_loss: 0.3610
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.3609 - val_accuracy: 1.0000 - val_loss: 0.3593
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 1.0000 - loss: 0.3592 - val_accuracy: 1.0000 - val_loss: 0.3577
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 103ms/step - accuracy: 1.0000 - loss: 0.3580 - val_accuracy: 1.0000 - val_loss: 0.3560
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.3565 - val_accuracy: 1.0000 - val_loss: 0.3544
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.3544 - val_accuracy: 1.0000 - val_loss: 0.3528
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.3528 - val_accuracy: 1.0000 - val_loss: 0.3512
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.3513 - val_accuracy: 1.0000 - val_loss: 0.3495
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3494 - val_accuracy: 1.0000 - val_loss: 0.3480
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3478 - val_accuracy: 1.0000 - val_loss: 0.3464
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3458 - val_accuracy: 1.0000 - val_loss: 0.3448
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.3443 - val_accuracy: 1.0000 - val_loss: 0.3432
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.3431 - val_accuracy: 1.0000 - val_loss: 0.3416
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3413 - val_accuracy: 1.0000 - val_loss: 0.3401
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.3404 - val_accuracy: 1.0000 - val_loss: 0.3386
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3390 - val_accuracy: 1.0000 - val_loss: 0.3370
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.3368 - val_accuracy: 1.0000 - val_loss: 0.3355
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3354 - val_accuracy: 1.0000 - val_loss: 0.3340
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.3338 - val_accuracy: 1.0000 - val_loss: 0.3325
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 1.0000 - loss: 0.3321 - val_accuracy: 1.0000 - val_loss: 0.3309
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.3308 - val_accuracy: 1.0000 - val_loss: 0.3295
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.3297 - val_accuracy: 1.0000 - val_loss: 0.3280
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.3276 - val_accuracy: 1.0000 - val_loss: 0.3265
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.3272 - val_accuracy: 1.0000 - val_loss: 0.3250
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.3250 - val_accuracy: 1.0000 - val_loss: 0.3236
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.3235 - val_accuracy: 1.0000 - val_loss: 0.3221
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3218 - val_accuracy: 1.0000 - val_loss: 0.3207
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3204 - val_accuracy: 1.0000 - val_loss: 0.3192
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3188 - val_accuracy: 1.0000 - val_loss: 0.3178
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.3178 - val_accuracy: 1.0000 - val_loss: 0.3164
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.3162 - val_accuracy: 1.0000 - val_loss: 0.3150
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.3153 - val_accuracy: 1.0000 - val_loss: 0.3136
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3136 - val_accuracy: 1.0000 - val_loss: 0.3122
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.3122 - val_accuracy: 1.0000 - val_loss: 0.3108
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.3114 - val_accuracy: 1.0000 - val_loss: 0.3094
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.3100 - val_accuracy: 1.0000 - val_loss: 0.3081
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.3079 - val_accuracy: 1.0000 - val_loss: 0.3067
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.3070 - val_accuracy: 1.0000 - val_loss: 0.3054
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.3054 - val_accuracy: 1.0000 - val_loss: 0.3040
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.3041 - val_accuracy: 1.0000 - val_loss: 0.3027
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.3028 - val_accuracy: 1.0000 - val_loss: 0.3014
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.3015 - val_accuracy: 1.0000 - val_loss: 0.3001
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.3000 - val_accuracy: 1.0000 - val_loss: 0.2988
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.2984 - val_accuracy: 1.0000 - val_loss: 0.2975
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 1.0000 - loss: 0.2970 - val_accuracy: 1.0000 - val_loss: 0.2962
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.2966 - val_accuracy: 1.0000 - val_loss: 0.2949
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.2950 - val_accuracy: 1.0000 - val_loss: 0.2936
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.2933 - val_accuracy: 1.0000 - val_loss: 0.2923
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.2923 - val_accuracy: 1.0000 - val_loss: 0.2911
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.2909 - val_accuracy: 1.0000 - val_loss: 0.2898
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.2897 - val_accuracy: 1.0000 - val_loss: 0.2886
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.2887 - val_accuracy: 1.0000 - val_loss: 0.2873
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2871 - val_accuracy: 1.0000 - val_loss: 0.2861
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.2859 - val_accuracy: 1.0000 - val_loss: 0.2850
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.2851 - val_accuracy: 1.0000 - val_loss: 0.2838
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.2834 - val_accuracy: 1.0000 - val_loss: 0.2826
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.2823 - val_accuracy: 1.0000 - val_loss: 0.2814
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.2813 - val_accuracy: 1.0000 - val_loss: 0.2803
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.2800 - val_accuracy: 1.0000 - val_loss: 0.2791
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2788 - val_accuracy: 1.0000 - val_loss: 0.2780
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 1.0000 - loss: 0.2781 - val_accuracy: 1.0000 - val_loss: 0.2768
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 98ms/step - accuracy: 1.0000 - loss: 0.2767 - val_accuracy: 1.0000 - val_loss: 0.2757
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2758 - val_accuracy: 1.0000 - val_loss: 0.2746
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.2748 - val_accuracy: 1.0000 - val_loss: 0.2735
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.2733 - val_accuracy: 1.0000 - val_loss: 0.2723
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 1.0000 - loss: 0.2721 - val_accuracy: 1.0000 - val_loss: 0.2712
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 1.0000 - loss: 0.2711 - val_accuracy: 1.0000 - val_loss: 0.2701
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.2712 - val_accuracy: 1.0000 - val_loss: 0.2691
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.2687 - val_accuracy: 1.0000 - val_loss: 0.2680
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.2686 - val_accuracy: 1.0000 - val_loss: 0.2669
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.2667 - val_accuracy: 1.0000 - val_loss: 0.2658